image: caster/wushuu_dsp
variables:
  GIT_SSL_NO_VERIFY: "1"

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - aclocal
    - automake --add-missing
    - autoconf
    - automake
    - ./configure
    - TBLIB_ROOT=/usr/local make
    - TBLIB_ROOT=/usr/local make install

test:
  stage: test
  script:
    - test/user_map_test
    - npm install
    - mocha



deploy:202:
  stage: deploy
  script:
    - echo "TODO"
