image: caster/wushuu_dsp

before_script:
  - aclocal
  - automake --add-missing
  - autoconf
  - automake
  - ./configure
  - TBLIB_ROOT=/usr/local make
  - TBLIB_ROOT=/usr/local make install

# test_user_map:
#   type: test
#   allow_failure: true
#   script:
#     - test/user_map_test


production:
  type: deploy
  script:
    - ./restart_fastcgi.sh
