image: caster/wushuu_dsp
variables:
  GIT_SSL_NO_VERIFY: "1"

build:
  stage: build
  script:
    - aclocal
    - automake --add-missing
    - autoconf
    - automake
    - ./configure
    - TBLIB_ROOT=/usr/local make
    - TBLIB_ROOT=/usr/local make install
    #test
    - test/user_map_test
    - GIT_SSL_NO_VERIFY=1 npm install
    - mocha
    #deploy
    - echo "TODO"
