image: caster/wushuu_dsp
variables:
  GIT_SSL_NO_VERIFY: "1"

build:
  stage: build
  script:
    - aclocal
    - automake --add-missing
    - autoconf
    - automake
    - ./configure
    - TBLIB_ROOT=/usr/local make
    - TBLIB_ROOT=/usr/local make install
    #test
    - MDB=TAIR test/CbaseMdb_test
    - MDB=REDIS  test/CbaseMdb_test
    - MDB=TAIR  test/user_map_test
    - MDB=REDIS  test/user_map_test
    - git config --global http.sslVerify false
    - cnpm install
    - MDB=TAIR mocha
    - MDB=REDIS mocha
    #deploy
    - echo "TODO"
