variables:
  TBLIB_ROOT: "/usr/local"
before_script:
  - autoconf
  - automake
  - ./configure
  - TBLIB_ROOT=/usr/local make
  - TBLIB_ROOT=/usr/local make install

start_cgi:
  script:
    - ./restart_fastcgi.sh

