before_script:

start_cgi:
  variables:
    TBLIB_ROOT: "/usr/local"
  script:
    - autoconf
    - automake
    - ./configure
    - TBLIB_ROOT=/usr/local make
    - TBLIB_ROOT=/usr/local make install
    - ./restart_fastcgi.sh

